name: Build with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'

    - name: Set up Maven 3.3
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        distribution: 'adopt'
        cache: 'maven'
        maven-version: '3.3.9'

    - name: Build with Maven
      run: mvn clean install