name: Build with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'
        java-package: 'jdk+fx'

    - name: Build with Maven
      env:
        NODE_OPTIONS: --openssl-legacy-provider
      run: mvn clean install
      